### ISSUE TITLE
CUDA/Vulkan Compatibility Issues with Insta360 stitcherSDK on Modern Systems

### ISSUE THREAD

**Issue by patina27** [Insta360Develop/Desktop-MediaSDK-Cpp#50]
# CUDA/Vulkan/GLFW Compatibility Issues with Insta360 stitcherSDK on Modern Systems

## Environment
- **SDK Version**: libMediaSDK-dev-3.0.1-20250418-amd64
- **OS**: Ubuntu 22.04
- **CUDA Driver Version**: 560.28.03
- **CUDA Runtime Version**: 12.6
- **GPU**: L4 (Google Cloud VM)

## Issue Description
We're experiencing compatibility issues when trying to use the stitcherSDK with GPU acceleration on systems with modern CUDA drivers:

1. The SDK appears to be compiled against CUDA 8.0.61, but we're running CUDA 12.6. 8.0.61 is a very very old build, not compatible with modern machines. 
2. When trying to use GPU-accelerated features (via `-enable_flowstate`), we encounter multiple errors:
```
Could not initialize the CUDA driver API CUDA_ERROR_SYSTEM_DRIVER_MISMATCH: system has unsupported display driver / cuda driver combination Cannot load libcudart.so.8.0.61 vulkan runtime init error
```

While CPU-only mode works by using the wrapper script that adds `-disable_cuda`, we'd like to leverage GPU acceleration for better performance.

3. The SDK assumes GLFW library dependencies, which makes it very problematic to run in headless environments:
   - We currently need to use `xvfb-run` as a workaround to create a virtual framebuffer
   - This adds complexity to our containerized deployment and serverless environments
   - A properly headless SDK without GUI dependencies would be much more suitable for our server-side video processing workflows

## Request
Could you provide one of the following:
1. An updated version of the SDK compatible with CUDA 11/12
2. Instructions for installing compatibility libraries to make the current SDK work with newer CUDA versions
3. Source-level access to rebuild the SDK against our current CUDA/Vulkan environment
4. A truly headless version that doesn't require X11/GLFW libraries or virtual framebuffers

Thank you for your assistance!

**Comment by thesidjway** [comment]
Hello is there any update on this? The SDK is almost unusable due to this for now

**Comment by Double-Insta360** [comment]
Can you tell me more about the usage scenarios and problems?

**Comment by Double-Insta360** [comment]
We have noticed this display issue and we will support headless in the next version.

**Comment by mitsiuTrimble** [comment]
Hi, I would also like to know if there are any updates on this issue? maybe specifically on the CUDA 12/13 versioning

**Comment by odmin4eg** [comment]
May I ask you to attach a docker file in which you can assemble your latest sdk? I have all the results coming to


```
 E ffmpeg:0000:  hevc_cuvid @ 0x73dc2c029c40 ctx->cvdl->cuvidCreateDecoder(&ctx->cudecoder, &cuinfo) failed
[06-03 13:41:49.723]  2831695 2831708 E ffmpeg:0000:  hevc_cuvid @ 0x73dc2c029c40  -> CUDA_ERROR_OUT_OF_MEMORY: out of memory
[06-03 13:41:49.723]  2831695 2831708 E ffmpeg:0000:  hevc_cuvid @ 0x73dc2c029c40 

[06-03 13:41:49.723]  2831695 2831708 E ffmpeg:0000:  hevc_cuvid @ 0x73dc2c029c40 cuvid decode callback error
```
Docker Image

`FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04`


$ nvidia-smi
```
Tue Jun  3 16:17:15 2025       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.129.06   Driver Version: 520.61.05    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:2B:00.0 Off |                  N/A |
|  0%   35C    P8    14W / 390W |  10753MiB / 12288MiB |      0%      Default |
```
I can't use my 2 insta x4 cameras, why did I buy them if I don't have a working linux stitcher  :(

**Comment by kanao-contineu** [comment]
> May I ask you to attach a docker file in which you can assemble your latest sdk? I have all the results coming to
> 
> ```
>  E ffmpeg:0000:  hevc_cuvid @ 0x73dc2c029c40 ctx->cvdl->cuvidCreateDecoder(&ctx->cudecoder, &cuinfo) failed
> [06-03 13:41:49.723]  2831695 2831708 E ffmpeg:0000:  hevc_cuvid @ 0x73dc2c029c40  -> CUDA_ERROR_OUT_OF_MEMORY: out of memory
> [06-03 13:41:49.723]  2831695 2831708 E ffmpeg:0000:  hevc_cuvid @ 0x73dc2c029c40 
> 
> [06-03 13:41:49.723]  2831695 2831708 E ffmpeg:0000:  hevc_cuvid @ 0x73dc2c029c40 cuvid decode callback error
> ```
> 
> Docker Image
> 
> `FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04`
> 
> $ nvidia-smi
> 
> ```
> Tue Jun  3 16:17:15 2025       
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 470.129.06   Driver Version: 520.61.05    CUDA Version: 11.8     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> |   0  NVIDIA GeForce ...  On   | 00000000:2B:00.0 Off |                  N/A |
> |  0%   35C    P8    14W / 390W |  10753MiB / 12288MiB |      0%      Default |
> ```
> 
> I can't use my 2 insta x4 cameras, why did I buy them if I don't have a working linux stitcher :(

Hi, I just noticed, but its a out of memory error, and your GPU almost seems full. Is this from running some other process? I've noticed MediaSDK takes around 2-2.5 gigs in GPU mem

**Comment by odmin4eg** [comment]
But the output of the nvidia-smi program shows that 10Gb is free.

**Comment by 3dsf** [comment]
I'd look into your Vulkan install.  I have basic gpu acceleration working with 
`libvulkan.so.1.3.204`

| Component | Version |
|-----------|---------|
| **OS** | Fedora 42 |
| **Kernel** | Linux (x86_64) |
| **CPU** | AMD Ryzen 9 7950X (16C/32T) |
| **iGPU** | AMD RDNA 2 (RADV RAPHAEL_MENDOCINO) |
| **dGPU** | NVIDIA GeForce RTX 2060 SUPER |
| **NVIDIA Driver** | 580.119.02 |
| **GCC** | 15.2.1 |
| **CUDA (system)** | 13 (`/usr/local/cuda-13/`) |
| **CUDA (SDK bundled)** | 8.0.61 (works via system driver API) |
| **Vulkan (system)** | 1.4.313 |
| **Vulkan (SDK compat)** | 1.3.204 (installed to `/opt/mediasdk/lib/`) |
| **MediaSDK** | 3.1.1.0 (installed to `/opt/mediasdk/`) |

---

Here's the summary of all issues encountered installing the Insta360 MediaSDK (Ubuntu 22.04 .deb) on Fedora 42 with running the SDKtest example (main.cc) with a basic test:

**Build Issues**

1. Missing <cstdint> include — SDK headers use uint8_t etc. without including <cstdint>. Worked implicitly on GCC 11 (Ubuntu), fails on GCC 14+ (Fedora). Fixed by patching the header.

2. libdc1394 soname mismatch — SDK links against libdc1394.so.25 (Ubuntu), Fedora ships .so.26. Fixed with a symlink.
 
3. RUNPATH vs RPATH — Modern GCC defaults to RUNPATH (DT_RUNPATH), which only resolves direct dependencies. Transitive deps like libdc1394.so.25 (loaded by libMediaSDK.so) weren't found. Fixed with --disable-new-dtags linker flag to use classic RPATH.
 
**Runtime Issues**
 
4. Vulkan loader version mismatch — SDK was built against Vulkan 1.3.204 (Ubuntu 22.04). The system's Vulkan 1.4.313 loader caused a segfault in vkEnumerateInstanceVersion() on the render thread — tested all three ICDs (NVIDIA, RADV, LVP), all crashed identically. Fixed by installing the Ubuntu 22.04 libvulkan.so.1.3.204 into lib.
 
5. CUDA encode/decode — Initially assumed broken due to the bundled libcudart.so.8.0.61 (CUDA 8.0) vs system CUDA 13. Turned out to work fine once Fix 4 was applied — the old runtime still talks to NVENC/NVDEC through the system's driver API. Result: ~5× speedup (20s vs 102s).

**Comment by humphrep** [comment]
Following up on the headless-support promise from 2025-05-07 — as of **MediaSDK 3.1.5** (released 2026-08-28) this is still not resolved, though the specific mechanism has changed since the original 3.0.1 report.

**What actually changed between 3.1.1 and 3.1.5, confirmed via direct log/binary comparison on the same headless Docker environment (g4dn.xlarge, Tesla T4, driver 595.91.07, no X server):**

- **3.1.1 initializes its renderer via `eglDisplayMgr`** — genuinely headless-safe. Every log shows a clean `eglDisplayMgr::SetupDisplay() called!` → a valid offscreen framebuffer, zero GL errors, stitching completes correctly with real per-parameter output.
- **3.1.5 never calls `eglDisplayMgr` at all** — that code is still compiled into `libMediaSDK.so` (confirmed via `strings`, the symbols are present), it's simply not being invoked. Instead it goes through a GLEW/GLX-based path that requires a real (or virtual) display: `GPULimits.cc: GLEW initialization failed`, followed by a cascade of `glGetError(): GL_INVALID_*` on every subsequent render call.

**This isn't just cosmetic warning noise — it silently degrades actual output.** Tested on a clip with a *known* accessory (premium/S-grade lens guard) attached: `-camera_accessory_type` 12 (premium, correct), 0 (none), 10 (dive case), and -1 (the new auto-detect value) all produced **byte-identical stitched output** on 3.1.5. Even `-stitch_type template` vs `optflow` produced identical bytes to each other. The same accessory-type comparison on 3.1.1 produces genuinely different output per value, as expected. `MediaSDKTest` still reports `process=100%` and exits 0 — nothing signals to the caller that anything degraded.

Right at the point this starts, every 3.1.5 run also logs `SeamlessBlender.cpp: bcv: unknown version of aiflow` — plausibly the GL-context failure cascading into whatever GPU-backed AIFlowV2 version-resolution step needs a working render context, though I can't fully confirm that specific causal link from outside your source.

**Ruled out before concluding this is environment-side, not us:** swapping in 3.1.1's original model files (no change), setting `NVIDIA_DRIVER_CAPABILITIES=all` (no change, though it did correctly mount the real NVIDIA GLX/EGL libraries — confirmed present), and running under Xvfb with a genuinely working virtual display (`glxinfo` succeeded, direct rendering yes — but `MediaSDKTest`'s own GLEW init still failed in the identical environment).

Given 3.1.1's EGL path already solved this exact class of problem, it seems like 3.1.5 introduced a new code path (tied to the new AIFlowV2 feature, based on the timing/co-occurrence) that doesn't share that fix. Happy to provide full logs/repro scripts if useful — this is blocking us from adopting 3.1.5 in a headless EC2 pipeline that's worked reliably on 3.1.1 for months.
